// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BlogPost struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewBlogPost struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type NewProject struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Language    string `json:"language"`
}

type Project struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Language    string `json:"language"`
	Description string `json:"description"`
}

type RegisterUser struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Password  string `json:"password"`
	Email     string `json:"email"`
}

type Token struct {
	Auth string `json:"auth"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Password  string `json:"password"`
	Email     string `json:"email"`
}
